os-features: take Craig's suggestion to use -Werror to test qsort_r; merge duplicate netpbm tests
git-svn-id: svn+ssh://astrometry.net/svn/trunk/src/astrometry@20111 03a3cea6-2c03-0410-ac9b-9271b1c66c29

diff --git a/util/Makefile b/util/Makefile
--- a/util/Makefile
+++ b/util/Makefile
@@ -294,52 +294,69 @@ install: $(PYTHON_LIBS) $(PYTHON_EXECS) $(PROGS) $(ANUTILS_H) $(ANFILES_LIB) $(A
 .PHONY: install
 
 os-features-config.h: os-features-test.c
+	@echo
 	@echo "---- Error messages in the next few commands are not necessarily bugs ----"
 	@echo "     (we're checking how things works on your computer)"
+	-rm -f os-features.log
 	( \
 	 (($(CC) -o os-features-test-canonicalize \
-	   $(CFLAGS) -DTEST_CANONICALIZE_FILE_NAME $(LDFLAGS) $^  > /dev/null && \
-	   ./os-features-test-canonicalize > /dev/null && \
+	   $(CFLAGS) -DTEST_CANONICALIZE_FILE_NAME $(LDFLAGS) $^  >> os-features.log && \
+	   ./os-features-test-canonicalize >> os-features.log && \
 	   echo "#define NEED_CANONICALIZE_FILE_NAME 0") \
 	|| echo "#define NEED_CANONICALIZE_FILE_NAME 1") \
 	; \
 	 (($(CC) -o os-features-test-declare-qsort \
-	   $(CFLAGS) -DTEST_DECLARE_QSORT_R $(LDFLAGS) $^ > /dev/null && \
-	   ./os-features-test-declare-qsort > /dev/null && \
+	   $(CFLAGS) -DTEST_DECLARE_QSORT_R $(LDFLAGS) $^ >> os-features.log && \
+	   ./os-features-test-declare-qsort >> os-features.log && \
 	   echo "#define NEED_DECLARE_QSORT_R 1") \
 	|| echo "#define NEED_DECLARE_QSORT_R 0") \
 	; \
 	 (($(CC) -o os-features-test-qsort \
-	   $(CFLAGS) -DTEST_QSORT_R $(LDFLAGS) $^ > /dev/null && \
-	   ./os-features-test-qsort > /dev/null && \
+	   $(CFLAGS) -DTEST_QSORT_R $(LDFLAGS) $^ >> os-features.log && \
+	   ./os-features-test-qsort >> os-features.log && \
 	   echo "#define NEED_QSORT_R 0") \
 	|| echo "#define NEED_QSORT_R 1") \
 	; \
-	 (($(CC) -o os-features-test-swap-qsort \
-	   $(CFLAGS) -DTEST_SWAP_QSORT_R $(LDFLAGS) $^ > /dev/null && \
-	   ./os-features-test-swap-qsort > /dev/null && \
+	 (($(CC) -Werror -o os-features-test-swap-qsort \
+	   $(CFLAGS) -DTEST_SWAP_QSORT_R $(LDFLAGS) $^ >> os-features.log && \
+	   ./os-features-test-swap-qsort >> os-features.log && \
 	   echo "#define NEED_SWAP_QSORT_R 1") \
 	|| echo "#define NEED_SWAP_QSORT_R 0") \
 	; \
 	 (($(CC) -o os-features-test-netpbm \
-	   $(CFLAGS) -DTEST_NETPBM $(LDFLAGS) $(NETPBM_INC_ORIG) $(NETPBM_LIB_ORIG) $^ > /dev/null && \
-	   ./os-features-test-netpbm > /dev/null && \
+	   $(CFLAGS) -DTEST_NETPBM $(LDFLAGS) $(NETPBM_INC_ORIG) $(NETPBM_LIB_ORIG) $^ >> os-features.log && \
+	   ./os-features-test-netpbm >> os-features.log && \
 	   echo "#define HAVE_NETPBM 1") \
 	|| echo "#define HAVE_NETPBM 0") \
 	; \
 	echo) > $@
 	@echo "--------------- End of expected error messages -----------------"
+	@echo
 
 makefile.os-features: os-features-test.c
+	@echo
+	@echo "---- Error messages in the next few commands are not necessarily bugs ----"
+	@echo "     (we're checking how things works on your computer)"
+	-rm -f os-features-makefile.log
 	( \
 	 echo "# This file is generated by util/Makefile."; \
 	 (($(CC) -o os-features-test-netpbm-make \
-	   $(CFLAGS) -DTEST_NETPBM_MAKE $(LDFLAGS) $(NETPBM_INC_ORIG) $(NETPBM_LIB_ORIG) $^ > /dev/null && \
-	   ./os-features-test-netpbm-make > /dev/null && \
+	   $(CFLAGS) -DTEST_NETPBM_MAKE $(LDFLAGS) $(NETPBM_INC_ORIG) $(NETPBM_LIB_ORIG) $^ >> os-features-makefile.log && \
+	   ./os-features-test-netpbm-make >> os-features-makefile.log && \
 	   echo "HAVE_NETPBM := yes") \
-	|| echo "# Don't HAVE_NETPBM.") \
+	|| (echo "# Astrometry.net didn't find netpbm; not setting HAVE_NETPBM."; \
+		echo "# See os-features-makefile.log for details."; \
+		echo "# To re-run this test, do 'make reconfig; make makefile.os-features' (in the 'util' directory)"; \
+		echo "# Or to do it yourself, just uncomment this line:"; \
+		echo "# HAVE_NETPBM := yes")) \
 	; \
 	echo) > $@
+	@echo "--------------- End of expected error messages -----------------"
+	@echo
+
+reconfig:
+	-rm -f os-features-config.h makefile.os-features
+.PHONY: reconfig
 
 ALL_OBJ += os-features.o
 ALL_TARGETS := os-features-test.o \
